# Generated by Django 5.2.6 on 2025-11-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_given', models.BooleanField(default=False)),
                ('reward_type', models.CharField(choices=[('Enrollment', 'Enrollment'), ('Onboarding', 'Onboarding')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('reward_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
