# Generated by Django 5.2.6 on 2026-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursemodule_coursesession_studentsessionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
