# Generated by Django 5.2.6 on 2026-01-10 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursemodule_coursesession_studentsessionprogress'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('tutor', 'date', 'start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='classschedule',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_schedules', to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_schedules', to='courses.coursesession'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='meet_link',
            field=models.URLField(blank=True, help_text='Google Meet / Zoom link', null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='is_booked',
        ),
    ]
