# Generated by Django 5.2.6 on 2026-01-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignmentsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='resubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(upload_to='assignments/'),
        ),
    ]
